/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "haptic": {
    name: "haptic",
    description: "Trigger haptic feedback on mobile devices.",
    type: "registry:lib",
    files: [{
      path: "src/registry/lib/haptic/haptic.ts",
      type: "registry:lib",
      target: "@lib/haptic.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/haptic/haptic.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "use-sound": {
    name: "use-sound",
    description: "Hook for playing sound effects with volume, playback rate, and interrupt controls.",
    type: "registry:hook",
    files: [{
      path: "src/registry/hooks/sound/use-sound.ts",
      type: "registry:hook",
      target: "@hooks/sound/use-sound.ts",
    },{
      path: "src/registry/lib/sound/sound-engine.ts",
      type: "registry:lib",
      target: "@lib/sound/sound-engine.ts",
    },{
      path: "src/registry/lib/sound/sound-types.ts",
      type: "registry:lib",
      target: "@lib/sound/sound-types.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/hooks/sound/use-sound.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-flip": {
    name: "text-flip",
    description: "Animated text that cycles through items with a smooth flip transition.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/text-flip/text-flip.tsx",
      type: "registry:component",
      target: "@components/text-flip.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/text-flip/text-flip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "apple-hello-effect": {
    name: "apple-hello-effect",
    description: "SVG writing animation inspired by Apple's Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect-english.tsx",
      type: "registry:component",
      target: "@components/apple-hello-effect-english.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect-english.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "apple-hello-effect-hindi": {
    name: "apple-hello-effect-hindi",
    description: "SVG writing animation inspired by Apple's Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect-hindi.tsx",
      type: "registry:component",
      target: "@components/apple-hello-effect-hindi.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect-hindi.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "apple-hello-effect-spanish": {
    name: "apple-hello-effect-spanish",
    description: "SVG writing animation inspired by Apple's Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect-spanish.tsx",
      type: "registry:component",
      target: "@components/apple-hello-effect-spanish.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect-spanish.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "apple-hello-effect-vietnamese": {
    name: "apple-hello-effect-vietnamese",
    description: "SVG writing animation inspired by Apple's Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect-vietnamese.tsx",
      type: "registry:component",
      target: "@components/apple-hello-effect-vietnamese.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect-vietnamese.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "wheel-picker": {
    name: "wheel-picker",
    description: "iOS-like wheel picker for React with smooth inertia scrolling and infinite loop support.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/wheel-picker/wheel-picker.tsx",
      type: "registry:component",
      target: "@components/wheel-picker.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/wheel-picker/wheel-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "chevrons-up-down-icon": {
    name: "chevrons-up-down-icon",
    description: "Animated chevrons icon that morphs between up and down directions.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/chevrons-up-down-icon/chevrons-up-down-icon.tsx",
      type: "registry:component",
      target: "@components/chevrons-up-down-icon.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/chevrons-up-down-icon/chevrons-up-down-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "shimmering-text": {
    name: "shimmering-text",
    description: "Smooth, light-sweeping shimmer animation for text.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/shimmering-text/shimmering-text.tsx",
      type: "registry:component",
      target: "@components/shimmering-text.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/shimmering-text/shimmering-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "slide-to-unlock": {
    name: "slide-to-unlock",
    description: "Interactive slider inspired by the classic iPhone slide-to-unlock gesture.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/slide-to-unlock/slide-to-unlock.tsx",
      type: "registry:component",
      target: "@components/slide-to-unlock.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/slide-to-unlock/slide-to-unlock.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "testimonial": {
    name: "testimonial",
    description: "Display user feedback with author info, avatar, and verified badge.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial/testimonial.tsx",
      type: "registry:component",
      target: "@components/testimonial.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial/testimonial.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "scroll-fade-effect": {
    name: "scroll-fade-effect",
    description: "Fade content edges as you scroll, for both vertical and horizontal layouts.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/scroll-fade-effect/scroll-fade-effect.tsx",
      type: "registry:component",
      target: "@components/scroll-fade-effect.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/scroll-fade-effect/scroll-fade-effect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "copy-button": {
    name: "copy-button",
    description: "Copy text to clipboard with visual, haptic, and audio feedback.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/copy-button/copy-button.tsx",
      type: "registry:component",
      target: "@components/copy-button.tsx",
    },{
      path: "src/hooks/use-copy-to-clipboard.ts",
      type: "registry:hook",
      target: "@hooks/use-copy-to-clipboard.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/copy-button/copy-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "code-block-command": {
    name: "code-block-command",
    description: "Display install commands with package manager switcher and copy button.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/code-block-command/code-block-command.tsx",
      type: "registry:component",
      target: "@components/code-block-command.tsx",
    },{
      path: "src/components/base/ui/tabs.tsx",
      type: "registry:component",
      target: "@components/tabs.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/code-block-command/code-block-command.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "testimonial-spotlight": {
    name: "testimonial-spotlight",
    description: "Testimonial card with spotlight effect on hover.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial-spotlight/testimonial-spotlight.tsx",
      type: "registry:component",
      target: "@components/testimonial-spotlight.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial-spotlight/testimonial-spotlight.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "glow-card-grid": {
    name: "glow-card-grid",
    description: "Display cards with glowing border and background effects.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/glow-card-grid/glow-card-grid.tsx",
      type: "registry:component",
      target: "@components/glow-card-grid.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/glow-card-grid/glow-card-grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "middle-truncation": {
    name: "middle-truncation",
    description: "Truncate text in the middle while preserving start and end.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/middle-truncation/middle-truncation.tsx",
      type: "registry:component",
      target: "@components/middle-truncation.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/middle-truncation/middle-truncation.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["typography"],
    meta: undefined,
  },
  "twemoji": {
    name: "twemoji",
    description: "Render Unicode emoji as Twemoji SVG images inline with text.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/twemoji/twemoji.tsx",
      type: "registry:component",
      target: "@components/twemoji.tsx",
    },{
      path: "src/registry/components/twemoji/lib/twemoji-regex.ts",
      type: "registry:lib",
      target: "@lib/twemoji-regex.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/twemoji/twemoji.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["typography"],
    meta: undefined,
  },
  "elastic-slider": {
    name: "elastic-slider",
    description: "Slider with elastic rubber-band drag and magnetic snap feedback.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/elastic-slider/elastic-slider.tsx",
      type: "registry:component",
      target: "@components/elastic-slider.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/elastic-slider/elastic-slider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "contribution-graph": {
    name: "contribution-graph",
    description: "A GitHub-style contribution graph component that displays activity levels over time.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/contribution-graph/contribution-graph.tsx",
      type: "registry:component",
      target: "@components/contribution-graph.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/contribution-graph/contribution-graph.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "github-contributions": {
    name: "github-contributions",
    description: "Visualize year-long GitHub contribution activity with daily counts, tooltips, and a profile link.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/github-contributions/github-contributions.tsx",
      type: "registry:component",
      target: "@components/github-contributions.tsx",
    },{
      path: "src/registry/components/github-contributions/lib/get-cached-contributions.ts",
      type: "registry:lib",
      target: "@lib/get-cached-contributions.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/github-contributions/github-contributions.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "fluid-gradient-text": {
    name: "fluid-gradient-text",
    description: "Render text with a fluid gradient that shifts with pointer movement.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/fluid-gradient-text/fluid-gradient-text.tsx",
      type: "registry:component",
      target: "@components/fluid-gradient-text.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/fluid-gradient-text/fluid-gradient-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "brand-assets-menu": {
    name: "brand-assets-menu",
    description: "Context menu for copying brand SVGs and opening asset links.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/brand-assets-menu/brand-assets-menu.tsx",
      type: "registry:component",
      target: "@components/brand-assets-menu.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/brand-assets-menu/brand-assets-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["menus"],
    meta: undefined,
  },
  "icon-swap": {
    name: "icon-swap",
    description: "Animate icon swaps with scale, blur, and fade transitions.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/icon-swap/icon-swap.tsx",
      type: "registry:component",
      target: "@components/icon-swap.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/icon-swap/icon-swap.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "spinning-circular-text": {
    name: "spinning-circular-text",
    description: "Text arranged in a circle with a continuous spinning animation.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/spinning-circular-text/spinning-circular-text.tsx",
      type: "registry:component",
      target: "@components/spinning-circular-text.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/spinning-circular-text/spinning-circular-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "theme-switcher": {
    name: "theme-switcher",
    description: "Toggle between system, light, and dark themes in Next.js apps.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/theme-switcher/theme-switcher.tsx",
      type: "registry:component",
      target: "@components/theme-switcher.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/theme-switcher/theme-switcher.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "apple-hello-effect-languages-demo": {
    name: "apple-hello-effect-languages-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-languages-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/apple-hello-effect-languages-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-switcher-demo": {
    name: "theme-switcher-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-switcher-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/theme-switcher-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmering-text-demo-02": {
    name: "shimmering-text-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/shimmering-text-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "slide-to-unlock-demo": {
    name: "slide-to-unlock-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/slide-to-unlock-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "code-block-command-demo": {
    name: "code-block-command-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/code-block-command-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/code-block-command-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/copy-button-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/copy-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonial-spotlight-demo": {
    name: "testimonial-spotlight-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonial-spotlight-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonial-spotlight-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "middle-truncation-demo": {
    name: "middle-truncation-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/middle-truncation-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/middle-truncation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "twemoji-demo": {
    name: "twemoji-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/twemoji-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/twemoji-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-toggle-effect-demo": {
    name: "theme-toggle-effect-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-toggle-effect-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/theme-toggle-effect-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "elastic-slider-demo": {
    name: "elastic-slider-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/elastic-slider-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/elastic-slider-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-demo": {
    name: "github-contributions-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "fluid-gradient-text-demo": {
    name: "fluid-gradient-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/fluid-gradient-text-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/fluid-gradient-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "brand-assets-menu-demo": {
    name: "brand-assets-menu-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/brand-assets-menu-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/brand-assets-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "icon-swap-demo": {
    name: "icon-swap-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/icon-swap-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/icon-swap-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-flip-demo": {
    name: "text-flip-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/text-flip-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/text-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "wheel-picker-demo": {
    name: "wheel-picker-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/wheel-picker-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}